FORMAT: 1A
HOST: http://localhost:3000

# Node API Base

API boilerplate project for NodeJS with Typescript

## Server [/status]

### Server status [GET]

Check if the server is online

+ Response 200 (application/json)

    + Body

            {
                "online": true
            }

## User Collection [/user]

### Create User [POST]

Create a new user in the app to authenticate afterwards

+ Request (application/json)

        {
            "email": "mail@example.com",
            "password": "shhhh"
        }

+ Response 200 (application/json)

    + Headers

            token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNmMGU2N2NlLWFlOWItNDIwOC1hOGI0LWY1NGIyNmE0OWQxZiIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNTM3MzEyMDExfQ.fMrmKpkUpc3mf-Ol7j-kwL99mX74L27oP7FZApTGxSU

    + Body

            {
                "id": "3f0e67ce-ae9b-4208-a8b4-f54b26a49d1f",
                "email": "mail@example.com"
            }

## Admin Collection [/admin]

### Create Admin [POST]

Create a new admin in the app to manage the app. An admin 
can only be created by other admin (authentication and authorization 
required for this operation)

+ Request (application/json)

        {
            "email": "mail@example.com",
            "password": "shhhh"
        }

+ Response 200 (application/json)

    + Headers

            token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNmMGU2N2NlLWFlOWItNDIwOC1hOGI0LWY1NGIyNmE0OWQxZiIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNTM3MzEyMDExfQ.fMrmKpkUpc3mf-Ol7j-kwL99mX74L27oP7FZApTGxSU

    + Body

            {
                "id": "3f0e67ce-ae9b-4208-a8b4-f54b26a49d1f",
                "email": "mail@example.com"
            }


## Authorization [/auth]

### Login [POST]

Authenticate in the app

+ Request (application/json)

        {
            "email": "mail@example.com",
            "password": "shhhh"
        }

+ Response 204 (application/json)

    + Headers

            token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNmMGU2N2NlLWFlOWItNDIwOC1hOGI0LWY1NGIyNmE0OWQxZiIsInJvbGUiOiJSZWd1bGFyIiwiaWF0IjoxNTM3MzEyMDExfQ.fMrmKpkUpc3mf-Ol7j-kwL99mX74L27oP7FZApTGxSU